# Generated by Django 3.0.1 on 2020-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cpassword',
            new_name='usercpassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='userfname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='userlname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='userpassword',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
