# Generated by Django 3.0.1 on 2020-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200210_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Fname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Lname',
            field=models.CharField(max_length=60),
        ),
    ]
