# Generated by Django 3.0.1 on 2020-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200210_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('enquiry_name', models.CharField(max_length=60)),
                ('enquiry_email', models.EmailField(default=False, max_length=100)),
                ('enquiry_subject', models.CharField(max_length=1000)),
                ('enquiry_message', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_user',
            new_name='admin_id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(default=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default=False, max_length=80),
        ),
    ]
